apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend-green
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
      version: v1.0.1
  template:
    metadata:
      labels:
        service: frontend
        version: v1.0.1
        api: external
    spec:
      containers:
        - image: 622817277005.dkr.ecr.eu-west-2.amazonaws.com/frontend:latest
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "150m"
            limits:
              memory: "2048Mi"
              cpu: "300m"
      restartPolicy: Always