apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-green
  name: frontend-green
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 80
  selector:
    service: frontend-green
    version: v1.0.1