apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy-green
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    service: reverse-proxy
    version: v1.0.1