version: "3"
services:
  reverse-proxy:
    image: reverse-proxy
    ports:
      - "3001"
    restart: always
    depends_on:
      - backend-blogs
  backend-blogs:
    image: backend-blogs
  frontend:
    image: frontend
    ports:
      - "3000:80"
