apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-blue
  name: frontend-blue
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 80
  selector:
    service: frontend-blue
    version: v1.1.0