apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend-blue
  name: frontend-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend-blue
      version: v1.0.0
  template:
    metadata:
      labels:
        service: frontend-blue
        version: v1.0.0
        api: external
    spec:
      containers:
        - image: 622817277005.dkr.ecr.eu-west-2.amazonaws.com/frontend:v1
          name: frontend-blue
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "150m"
            limits:
              memory: "2048Mi"
              cpu: "300m"
      restartPolicy: Always