apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverse-proxy
      version: v1.0.0
  template:
    metadata:
      labels:
        service: reverse-proxy
        version: v1.0.0
    spec:
      containers:
        - image: 622817277005.dkr.ecr.eu-west-2.amazonaws.com/reverse-proxy:v1
          name: reverse-proxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "150m"
            limits:
              memory: "1024Mi"
              cpu: "300m"
          ports:
            - containerPort: 3001
      restartPolicy: Always